# Generated by Django 4.2.9 on 2024-01-28 17:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('locations', '0005_rename_location_locations'),
    ]

    operations = [
        migrations.CreateModel(
            name='Providers',
            fields=[
                ('pr_id', models.AutoField(primary_key=True, serialize=False)),
                ('pr_name', models.CharField(max_length=100)),
                ('lo_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='locations.locations')),
            ],
        ),
    ]
