# Generated by Django 4.2.9 on 2024-02-03 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('providers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='providers',
            name='pr_webacc',
            field=models.JSONField(default={}),
            preserve_default=False,
        ),
    ]
