# Generated by Django 5.0.1 on 2024-02-05 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('providers', '0003_actiontypes_actionsmaster_actionsdetail'),
    ]

    operations = [
        migrations.AddField(
            model_name='actionsdetail',
            name='ad_sc_id',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='actionsdetail',
            name='ad_sc_name',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='actionsdetail',
            name='ad_sc_val',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='actionsdetail',
            name='ad_sc_xp',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
