# Generated by Django 5.0.1 on 2024-02-06 16:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('providers', '0004_actionsdetail_ad_sc_id_actionsdetail_ad_sc_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='providers',
            name='pr_webacc',
        ),
    ]
