# Generated by Django 5.0.1 on 2024-02-11 18:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('providers', '0006_providers_pr_webacc'),
    ]

    operations = [
        migrations.CreateModel(
            name='Parameters',
            fields=[
                ('par_id', models.AutoField(primary_key=True, serialize=False)),
                ('par_name', models.CharField(max_length=50, unique=True)),
                ('par_value_number', models.FloatField(null=True)),
                ('par_value_string', models.TextField(null=True)),
                ('par_isnumber', models.BooleanField()),
                ('par_desc', models.CharField(max_length=200)),
                ('pr_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='providers.providers')),
            ],
        ),
    ]
