# Generated by Django 5.0.1 on 2024-02-18 16:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('providers', '0008_parameters_lc_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='parameters',
            name='pr_id',
        ),
    ]
