# Generated by Django 5.0.1 on 2024-02-18 16:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('providers', '0010_actionsmaster_lc_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='actionsmaster',
            name='pr_id',
        ),
    ]
