# Generated by Django 5.0.1 on 2024-02-18 16:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('providers', '0011_remove_actionsmaster_pr_id'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Providers',
        ),
    ]
