# Generated by Django 5.0.1 on 2024-02-18 16:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0006_locations_pr_name_locations_pr_webacc'),
        ('providers', '0012_delete_providers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actionsmaster',
            name='lc_id',
            field=models.ForeignKey(default=42, on_delete=django.db.models.deletion.CASCADE, to='locations.locations'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='parameters',
            name='lc_id',
            field=models.ForeignKey(default=42, on_delete=django.db.models.deletion.CASCADE, to='locations.locations'),
            preserve_default=False,
        ),
    ]
