# Generated by Django 5.0.1 on 2024-02-22 23:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('providers', '0013_alter_actionsmaster_lc_id_alter_parameters_lc_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActionMTypes',
            fields=[
                ('at_id', models.AutoField(primary_key=True, serialize=False)),
                ('at_name', models.CharField(max_length=50)),
                ('at_desc', models.CharField(max_length=200)),
            ],
        ),
        migrations.RenameModel(
            old_name='ActionTypes',
            new_name='ActionDTypes',
        ),
    ]
