# Generated by Django 5.0.1 on 2024-02-22 23:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('providers', '0014_actionmtypes_rename_actiontypes_actiondtypes'),
    ]

    operations = [
        migrations.AddField(
            model_name='actionsmaster',
            name='am_type',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='providers.actionmtypes'),
            preserve_default=False,
        ),
    ]
