# Generated by Django 5.0.1 on 2024-02-23 00:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('providers', '0015_actionsmaster_am_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='actionsmaster',
            name='am_name',
        ),
    ]
