# Generated by Django 5.0.1 on 2024-02-27 15:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('providers', '0016_remove_actionsmaster_am_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='actionsmaster',
            old_name='lc_id',
            new_name='lo_id',
        ),
    ]
