# Generated by Django 5.0.3 on 2024-03-15 13:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('providers', '0017_rename_lc_id_actionsmaster_lo_id'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Parameters',
        ),
    ]
