# Generated by Django 5.0.1 on 2024-03-14 01:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('generators', '0001_initial'),
        ('locations', '0006_locations_pr_name_locations_pr_webacc'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Generator',
            new_name='Generators',
        ),
    ]
