# Generated by Django 5.0.3 on 2024-03-15 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('generators', '0002_rename_generator_generators'),
    ]

    operations = [
        migrations.AddField(
            model_name='generators',
            name='gn_url',
            field=models.URLField(default='NA'),
            preserve_default=False,
        ),
    ]
