# Generated by Django 5.0.1 on 2024-02-11 17:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('locations', '0005_rename_location_locations'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProviderConsuptions',
            fields=[
                ('pc_id', models.AutoField(primary_key=True, serialize=False)),
                ('pc_date', models.DateField()),
                ('pc_hour', models.SmallIntegerField()),
                ('pc_kWh', models.DecimalField(decimal_places=2, max_digits=7)),
                ('pc_kVARhL', models.DecimalField(decimal_places=2, max_digits=7)),
                ('pc_kVARhC', models.DecimalField(decimal_places=2, max_digits=7)),
                ('pc_kVARhP', models.DecimalField(decimal_places=2, max_digits=7)),
                ('pc_pf', models.DecimalField(decimal_places=2, max_digits=3)),
                ('lo_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='locations.locations')),
            ],
        ),
    ]
