# Generated by Django 5.0.1 on 2024-02-11 18:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='providerconsuptions',
            name='lo_id',
        ),
    ]
