# Generated by Django 5.0.1 on 2024-02-11 18:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('providers', '0006_providers_pr_webacc'),
        ('records', '0002_remove_providerconsuptions_lo_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='providerconsuptions',
            name='pr_id',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='providers.providers'),
            preserve_default=False,
        ),
    ]
