# Generated by Django 5.0.1 on 2024-02-11 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0003_providerconsuptions_pr_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='providerconsuptions',
            name='pc_kVARhC',
            field=models.DecimalField(decimal_places=2, max_digits=7, null=True),
        ),
        migrations.AlterField(
            model_name='providerconsuptions',
            name='pc_kVARhL',
            field=models.DecimalField(decimal_places=2, max_digits=7, null=True),
        ),
        migrations.AlterField(
            model_name='providerconsuptions',
            name='pc_kVARhP',
            field=models.DecimalField(decimal_places=2, max_digits=7, null=True),
        ),
        migrations.AlterField(
            model_name='providerconsuptions',
            name='pc_pf',
            field=models.DecimalField(decimal_places=2, max_digits=3, null=True),
        ),
    ]
