# Generated by Django 5.0.1 on 2024-02-12 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('providers', '0007_parameters'),
        ('records', '0005_alter_providerconsuptions_pc_kwh'),
    ]

    operations = [
        migrations.CreateModel(
            name='Consup_detail',
            fields=[
                ('cd', models.AutoField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.RenameModel(
            old_name='ProviderConsuptions',
            new_name='Consup_Master',
        ),
    ]
