# Generated by Django 5.0.1 on 2024-02-18 16:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0006_locations_pr_name_locations_pr_webacc'),
        ('records', '0007_rename_cd_consup_detail_cd_id_consup_detail_cm_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='consup_master',
            name='lc_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='locations.locations'),
        ),
    ]
