# Generated by Django 5.0.1 on 2024-02-18 16:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0008_consup_master_lc_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='consup_master',
            name='pr_id',
        ),
    ]
