# Generated by Django 5.0.1 on 2024-02-27 15:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0010_alter_consup_master_lc_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='consup_master',
            old_name='lc_id',
            new_name='lo_id',
        ),
    ]
