# Generated by Django 5.0.1 on 2024-03-14 02:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consumers', '0001_initial'),
        ('generators', '0002_rename_generator_generators'),
        ('records', '0013_consup_provider_lo_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Consup_generator',
            fields=[
                ('cd_id', models.AutoField(primary_key=True, serialize=False)),
                ('cm_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='records.consup_master')),
                ('gn_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='generators.generators')),
            ],
        ),
        migrations.CreateModel(
            name='Consup_meter',
            fields=[
                ('cd_id', models.AutoField(primary_key=True, serialize=False)),
                ('cm_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='records.consup_master')),
                ('mt_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='consumers.meters')),
            ],
        ),
    ]
