# Generated by Django 5.0.1 on 2024-03-14 02:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0014_consup_generator_consup_meter'),
    ]

    operations = [
        migrations.AddField(
            model_name='consup_generator',
            name='pc_kVARhC',
            field=models.DecimalField(decimal_places=2, max_digits=7, null=True),
        ),
        migrations.AddField(
            model_name='consup_generator',
            name='pc_kVARhL',
            field=models.DecimalField(decimal_places=2, max_digits=7, null=True),
        ),
        migrations.AddField(
            model_name='consup_generator',
            name='pc_kVARhP',
            field=models.DecimalField(decimal_places=2, max_digits=7, null=True),
        ),
        migrations.AddField(
            model_name='consup_generator',
            name='pc_kWh',
            field=models.DecimalField(decimal_places=2, max_digits=7, null=True),
        ),
        migrations.AddField(
            model_name='consup_generator',
            name='pc_pf',
            field=models.DecimalField(decimal_places=2, max_digits=3, null=True),
        ),
        migrations.AddField(
            model_name='consup_meter',
            name='pc_kVARhC',
            field=models.DecimalField(decimal_places=2, max_digits=7, null=True),
        ),
        migrations.AddField(
            model_name='consup_meter',
            name='pc_kVARhL',
            field=models.DecimalField(decimal_places=2, max_digits=7, null=True),
        ),
        migrations.AddField(
            model_name='consup_meter',
            name='pc_kVARhP',
            field=models.DecimalField(decimal_places=2, max_digits=7, null=True),
        ),
        migrations.AddField(
            model_name='consup_meter',
            name='pc_kWh',
            field=models.DecimalField(decimal_places=2, max_digits=7, null=True),
        ),
        migrations.AddField(
            model_name='consup_meter',
            name='pc_pf',
            field=models.DecimalField(decimal_places=2, max_digits=3, null=True),
        ),
        migrations.AddField(
            model_name='consup_provider',
            name='pc_kVARhC',
            field=models.DecimalField(decimal_places=2, max_digits=7, null=True),
        ),
        migrations.AddField(
            model_name='consup_provider',
            name='pc_kVARhL',
            field=models.DecimalField(decimal_places=2, max_digits=7, null=True),
        ),
        migrations.AddField(
            model_name='consup_provider',
            name='pc_kVARhP',
            field=models.DecimalField(decimal_places=2, max_digits=7, null=True),
        ),
        migrations.AddField(
            model_name='consup_provider',
            name='pc_kWh',
            field=models.DecimalField(decimal_places=2, max_digits=7, null=True),
        ),
        migrations.AddField(
            model_name='consup_provider',
            name='pc_pf',
            field=models.DecimalField(decimal_places=2, max_digits=3, null=True),
        ),
    ]
