# Generated by Django 5.0.1 on 2024-03-14 02:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0015_consup_generator_pc_kvarhc_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='consup_master',
            name='lo_id',
        ),
        migrations.RemoveField(
            model_name='consup_master',
            name='pc_kVARhC',
        ),
        migrations.RemoveField(
            model_name='consup_master',
            name='pc_kVARhL',
        ),
        migrations.RemoveField(
            model_name='consup_master',
            name='pc_kVARhP',
        ),
        migrations.RemoveField(
            model_name='consup_master',
            name='pc_kWh',
        ),
        migrations.RemoveField(
            model_name='consup_master',
            name='pc_pf',
        ),
    ]
