# Generated by Django 4.2.9 on 2024-01-26 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Parameters',
            fields=[
                ('par_id', models.AutoField(primary_key=True, serialize=False)),
                ('par_name', models.CharField(max_length=50, unique=True)),
                ('par_value_number', models.FloatField(null=True)),
                ('par_value_string', models.TextField(null=True)),
                ('par_isnumber', models.BooleanField()),
            ],
        ),
    ]
