# Generated by Django 4.2.9 on 2024-02-03 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parameters', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='parameters',
            name='par_desc',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
    ]
