# Generated by Django 5.0.3 on 2024-03-17 03:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('parameters', '0002_parameters_par_desc'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='parameters',
            name='par_value_number',
        ),
    ]
