# Generated by Django 5.0.3 on 2024-03-15 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consumers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='meters',
            name='mt_url',
            field=models.URLField(default=''),
            preserve_default=False,
        ),
    ]
