# Generated by Django 4.2.9 on 2024-01-27 21:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='States',
            fields=[
                ('st_code', models.AutoField(primary_key=True, serialize=False)),
                ('st_name', models.CharField(max_length=50)),
                ('co_iso_num', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='locations.countries')),
            ],
        ),
        migrations.CreateModel(
            name='Cities',
            fields=[
                ('ct_code', models.AutoField(primary_key=True, serialize=False)),
                ('ct_name', models.CharField(max_length=50)),
                ('st_code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='locations.states')),
            ],
        ),
    ]
