# Generated by Django 4.2.9 on 2024-01-27 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0002_states_cities'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cities',
            name='ct_name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='states',
            name='st_name',
            field=models.CharField(max_length=100),
        ),
    ]
