# Generated by Django 4.2.9 on 2024-01-27 21:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0003_alter_cities_ct_name_alter_states_st_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('lo_id', models.AutoField(primary_key=True, serialize=False)),
                ('lo_name', models.CharField(max_length=100)),
                ('lo_addrl1', models.CharField(max_length=100)),
                ('lo_addrl2', models.CharField(max_length=100)),
                ('ct_code', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='locations.cities')),
            ],
        ),
    ]
