# Generated by Django 5.0.1 on 2024-02-18 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0005_rename_location_locations'),
    ]

    operations = [
        migrations.AddField(
            model_name='locations',
            name='pr_name',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='locations',
            name='pr_webacc',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
    ]
